### ISSUE TITLE
Changelog Enforcer sometimes doesn't run...or skip?

### ISSUE THREAD

**Issue by mathomp4** [dangoslen/changelog-enforcer#149] opened 2021-08-30 19:35 UTC
This is a weird one for the guru, @dangoslen. I've been happily using changelog enforcer but a recent foray into "automatic" PRs with [action-pull-request](https://github.com/devops-infra/action-pull-request) by @ChristophShyper has led to an oddity. Namely, when an automatic PR to `develop` is triggered, see here:

https://github.com/GEOS-ESM/MAPL/pull/1008

for some reason, the changelog enforcer gets...stuck. It's like the action never gets triggered. Whether or not there is a changelog update, it doesn't run. I tried to solve it by always adding a "Skip Changelog" to the auto PR (since, well, this sort of PR doesn't matter for changelog in truth), but even then, it doesn't skip. I can "fix" it by just removing/relabeling with some label like "Skip Changelog" and then the action is triggered.

I'm wondering if you have any ideas. Perhaps there is some weird combination between action-pull-request and changelog-enforcer? It's baffling me.

**Comment by mathomp4** [comment] 2021-08-30 19:36
GitHub says:

> changelog Expected — Waiting for status to be reported

and never moves from that...

**Comment by mathomp4** [comment] 2021-08-30 19:44
And I suppose my [changelog-enforcer.yml](https://github.com/GEOS-ESM/MAPL/blob/develop/.github/workflows/changelog-enforcer.yml) could have a bug, but it's pretty boring.

**Comment by dangoslen** [comment] 2021-08-30 19:54
I've seen this happen too on pull requests generated/opened from automation. I've always been able to remove a label and then re-add it after a few seconds. 😔 I know that isn't optimal. I'm not sure what the issue is - but I can try looking into it. It seems like there is something with actions being triggered.

Have you tried [enabling debugging for actions](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging) on those automated PRs? I would be interested in seeing what that might look like if you are willing to enable it.

**Comment by mathomp4** [comment] 2021-08-30 20:19
> I've seen this happen too on pull requests generated/opened from automation. I've always been able to remove a label and then re-add it after a few seconds. 😔 I know that isn't optimal. I'm not sure what the issue is - but I can try looking into it. It seems like there is something with actions being triggered.

It's almost like automatic opening of PRs isn't considered a pull request opened. Weird!

> 
> Have you tried [enabling debugging for actions](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging) on those automated PRs? I would be interested in seeing what that might look like if you are willing to enable it.

Ooh. I didn't know about this. I'll enable it now (well, if I can figure out how, secrets always confuse me), and I'll see what happens

**Comment by ChristophShyper** [comment] 2021-09-06 12:02
> It's almost like automatic opening of PRs isn't considered a pull request opened. Weird!
> 

But it only happens for automation using GitHub Actions - worker creating pull request is not a consumer of `opened` for that pull request.  Maybe it should be merged into your `push-to-develop.yml`?
In my workflows I use AWS CodeBuild triggered on `PULL_REQUEST_CREATED` with a webhook to the same repository and it's doing its job.

**Comment by mathomp4** [comment] 2021-09-07 13:15
Hmm. interesting. @ChristophShyper You are saying put my changelog enforcer 'code' into `push-to-develop.yml` itself? I guess it can go after the "Run the action" job...

@dangoslen how would your action react to that? I mean, I'll still need my "usual" `changelog-enforcer.yml` in my repo for non-auto PRs. And branches are required to have that action occur. My fear is that GitHub Actions might go a bit nutty having the action run twice

**Comment by dangoslen** [comment] 2021-12-29 15:30
@mathomp4 I think this might be resolved with [`v3.0.0`](https://github.com/dangoslen/changelog-enforcer/releases/tag/v3.0.0)

**Comment by dangoslen** [comment] 2022-02-03 14:51
@mathomp4 did v3.0 fix your issue?

**Closed** 2022-09-23 21:09 UTC
